# Generated by Django 4.2.7 on 2023-12-15 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autos', to=settings.AUTH_USER_MODEL)),
                ('transaccion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.transaccion')),
            ],
        ),
    ]
