# Generated by Django 4.2.7 on 2023-12-10 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apiadmin', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autos', to='apiadmin.usuario')),
                ('transaccion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.transaccion')),
            ],
        ),
    ]
