# Generated by Django 4.2.7 on 2023-11-24 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
        ('apiuser', '0001_initial'),
        ('apiauto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='transaccion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.transaccion'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autos', to='apiuser.usuario'),
        ),
    ]
