# Generated by Django 4.2.7 on 2023-12-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('capacidad', models.PositiveIntegerField()),
                ('tarifa_hora', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
