# Generated by Django 4.2.7 on 2023-12-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiuser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='contrasena',
        ),
        migrations.AddField(
            model_name='usuario',
            name='dni',
            field=models.CharField(default=12345678, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default=12345678, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='photo_url',
            field=models.URLField(default=12345678),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='provider_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='provider_specific_uid',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
