# Generated by Django 4.2.8 on 2023-12-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiuser', '0002_rename_contraseña_usuario_contrasena_usuario_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(max_length=255, verbose_name='contraseña'),
        ),
    ]
