# Generated by Django 4.2.8 on 2023-12-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_instance', models.CharField(max_length=255)),
                ('api_token_instance', models.CharField(max_length=255)),
                ('name', models.CharField(default='Default Name', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(max_length=500, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('domain', models.TextField()),
                ('descripcion', models.TextField()),
                ('paths', models.ManyToManyField(to='apiservices.path')),
            ],
        ),
    ]
