# Generated by Django 4.2.8 on 2023-12-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiservices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsettings',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='telegramsettings',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramsettings',
            name='name',
            field=models.CharField(default='Default Name', max_length=255),
        ),
        migrations.AddField(
            model_name='whatsappsettings',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='whatsappsettings',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappsettings',
            name='name',
            field=models.CharField(default='Default Name', max_length=255),
        ),
    ]
