# Generated by Django 4.2.8 on 2023-12-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiservices', '0002_telegramsettings_active_telegramsettings_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsettings',
            name='chat_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
