# Generated by Django 4.2.8 on 2023-12-09 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiservices', '0004_remove_telegramsettings_chat_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramSettings',
        ),
    ]
