# Generated by Django 4.2.8 on 2023-12-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiservices', '0005_delete_telegramsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(max_length=1000, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('domain', models.TextField()),
                ('descripcion', models.TextField()),
                ('paths', models.ManyToManyField(to='apiservices.path')),
            ],
        ),
    ]
