# Generated by Django 4.2.7 on 2023-12-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('provider_id', models.CharField(max_length=255)),
                ('provider_specific_uid', models.CharField(max_length=255)),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('dni', models.CharField(max_length=8)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=255, verbose_name='contraseña')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('photo_url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
